//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication0524
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id_O { get; set; }
        public string OrderNo { get; set; }
        public int Id_P { get; set; }
    }
}
